name: Backend Continuous Integration
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches:
      - 'main'
jobs:
  LINT:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: starter/backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v3    
    - name: Install pipenv
      run: pip install pipenv
    - name: Install dependencies
      run: pipenv install --dev
    - name: Run lint
      run: |
        pipenv run lint
  TEST:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: starter/backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v3    
    - name: Install pipenv
      run: pip install pipenv
    - name: Install dependencies
      run: pipenv install --dev
    - name: Test with pytest
      run: |
        pipenv run test
  BUILD:
    runs-on: ubuntu-latest
    needs: [LINT, TEST]
    defaults:
      run:
        shell: bash
        working-directory: starter/backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v3    
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
     