name: Backend Continuous Integration
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches:
      - 'main'
jobs:
  LINT:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: starter/backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v3    
    - name: Install pipenv
      run: pip install pipenv
    - name: Install dependencies
      run: pipenv install --dev
    - name: Run lint
      run: pipenv run lint
    - name: Test with pytest
      run: |
        pipenv run lint
      # run: |
      #   pip install pytest pytest-cov
      #   pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

    
  ##############
  # TEST:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout Code
  #     uses: actions/checkout@v3

  #   - name: Use Node.js
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: '18.x'
  #   - name: Install dependencies
  #     run: cd starter/backend && python -m pip install --upgrade pip && pip install -r requirements.txt
  #   - name: Test with pytest
  #     run: cd starter/backend && pip test

  # BUILD:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout Code
  #     uses: actions/checkout@v3

  #   - name: Use Node.js
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: '18.x'
  

