name: Backend Continuous Deployment
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches:
      - 'main'
jobs:
  LINT:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: starter/backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v3    
    - name: Install pipenv
      run: pip install pipenv
    - name: Install dependencies
      run: pipenv install --dev
    - name: Run lint
      run: |
        pipenv run lint
  TEST:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: starter/backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v3    
    - name: Install pipenv
      run: pip install pipenv
    - name: Install dependencies
      run: pipenv install --dev
    - name: Test with pytest
      run: |
        pipenv run test
  BUILD:
    runs-on: ubuntu-latest
    needs: [LINT, TEST]
    defaults:
      run:
        shell: bash
        working-directory: starter/backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v3    
    - 
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - 
      name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - 
      name: Push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: backend
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
    
    - name: Deploy to Kubernetes
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
        kubectl apply -f k8s/service.yaml --kubeconfig=kubeconfig.yaml
        kubectl apply -f k8s/deployment.yaml --kubeconfig=kubeconfig.yaml  

